### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by bestlgc** [jadgle/DGM_4FP#19]
I read your code mfg_obstacle.py , but I can find config.json file .  where can i find i?

**Comment by matteobutano** [comment]
[config.json](https://github.com/jadgle/DGM_4FP/files/13072226/config.json)

Hi, here is the config file. To understand the meaning of the MFG parameters, you can read [Bonnemain et al.](https://arxiv.org/pdf/2201.08592.pdf)
